# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/victor/cocos2d-x

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/victor/cocos2d-x/Game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/cocos2d-x/Game/CMakeFiles /home/victor/cocos2d-x/Game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/cocos2d-x/Game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cocos2d

# Build rule for target.
cocos2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cocos2d
.PHONY : cocos2d

# fast build rule for target.
cocos2d/fast:
	$(MAKE) $(MAKESILENT) -f engine/cocos/core/CMakeFiles/cocos2d.dir/build.make engine/cocos/core/CMakeFiles/cocos2d.dir/build
.PHONY : cocos2d/fast

#=============================================================================
# Target rules for targets named external

# Build rule for target.
external: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external
.PHONY : external

# fast build rule for target.
external/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/CMakeFiles/external.dir/build.make engine/external/CMakeFiles/external.dir/build
.PHONY : external/fast

#=============================================================================
# Target rules for targets named ext_recast

# Build rule for target.
ext_recast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_recast
.PHONY : ext_recast

# fast build rule for target.
ext_recast/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/recast/CMakeFiles/ext_recast.dir/build.make engine/external/recast/CMakeFiles/ext_recast.dir/build
.PHONY : ext_recast/fast

#=============================================================================
# Target rules for targets named ext_tinyxml2

# Build rule for target.
ext_tinyxml2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_tinyxml2
.PHONY : ext_tinyxml2

# fast build rule for target.
ext_tinyxml2/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/tinyxml2/CMakeFiles/ext_tinyxml2.dir/build.make engine/external/tinyxml2/CMakeFiles/ext_tinyxml2.dir/build
.PHONY : ext_tinyxml2/fast

#=============================================================================
# Target rules for targets named ext_xxhash

# Build rule for target.
ext_xxhash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_xxhash
.PHONY : ext_xxhash

# fast build rule for target.
ext_xxhash/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/xxhash/CMakeFiles/ext_xxhash.dir/build.make engine/external/xxhash/CMakeFiles/ext_xxhash.dir/build
.PHONY : ext_xxhash/fast

#=============================================================================
# Target rules for targets named ext_xxtea

# Build rule for target.
ext_xxtea: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_xxtea
.PHONY : ext_xxtea

# fast build rule for target.
ext_xxtea/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/xxtea/CMakeFiles/ext_xxtea.dir/build.make engine/external/xxtea/CMakeFiles/ext_xxtea.dir/build
.PHONY : ext_xxtea/fast

#=============================================================================
# Target rules for targets named ext_clipper

# Build rule for target.
ext_clipper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_clipper
.PHONY : ext_clipper

# fast build rule for target.
ext_clipper/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/clipper/CMakeFiles/ext_clipper.dir/build.make engine/external/clipper/CMakeFiles/ext_clipper.dir/build
.PHONY : ext_clipper/fast

#=============================================================================
# Target rules for targets named ext_edtaa3func

# Build rule for target.
ext_edtaa3func: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_edtaa3func
.PHONY : ext_edtaa3func

# fast build rule for target.
ext_edtaa3func/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/edtaa3func/CMakeFiles/ext_edtaa3func.dir/build.make engine/external/edtaa3func/CMakeFiles/ext_edtaa3func.dir/build
.PHONY : ext_edtaa3func/fast

#=============================================================================
# Target rules for targets named ext_convertUTF

# Build rule for target.
ext_convertUTF: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_convertUTF
.PHONY : ext_convertUTF

# fast build rule for target.
ext_convertUTF/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/ConvertUTF/CMakeFiles/ext_convertUTF.dir/build.make engine/external/ConvertUTF/CMakeFiles/ext_convertUTF.dir/build
.PHONY : ext_convertUTF/fast

#=============================================================================
# Target rules for targets named ext_poly2tri

# Build rule for target.
ext_poly2tri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_poly2tri
.PHONY : ext_poly2tri

# fast build rule for target.
ext_poly2tri/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/poly2tri/CMakeFiles/ext_poly2tri.dir/build.make engine/external/poly2tri/CMakeFiles/ext_poly2tri.dir/build
.PHONY : ext_poly2tri/fast

#=============================================================================
# Target rules for targets named ext_md5

# Build rule for target.
ext_md5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_md5
.PHONY : ext_md5

# fast build rule for target.
ext_md5/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/md5/CMakeFiles/ext_md5.dir/build.make engine/external/md5/CMakeFiles/ext_md5.dir/build
.PHONY : ext_md5/fast

#=============================================================================
# Target rules for targets named ext_tolua

# Build rule for target.
ext_tolua: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_tolua
.PHONY : ext_tolua

# fast build rule for target.
ext_tolua/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/lua/tolua/CMakeFiles/ext_tolua.dir/build.make engine/external/lua/tolua/CMakeFiles/ext_tolua.dir/build
.PHONY : ext_tolua/fast

#=============================================================================
# Target rules for targets named ext_luasocket

# Build rule for target.
ext_luasocket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_luasocket
.PHONY : ext_luasocket

# fast build rule for target.
ext_luasocket/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/lua/luasocket/CMakeFiles/ext_luasocket.dir/build.make engine/external/lua/luasocket/CMakeFiles/ext_luasocket.dir/build
.PHONY : ext_luasocket/fast

#=============================================================================
# Target rules for targets named ext_unzip

# Build rule for target.
ext_unzip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_unzip
.PHONY : ext_unzip

# fast build rule for target.
ext_unzip/fast:
	$(MAKE) $(MAKESILENT) -f engine/external/unzip/CMakeFiles/ext_unzip.dir/build.make engine/external/unzip/CMakeFiles/ext_unzip.dir/build
.PHONY : ext_unzip/fast

#=============================================================================
# Target rules for targets named luacocos2d

# Build rule for target.
luacocos2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 luacocos2d
.PHONY : luacocos2d

# fast build rule for target.
luacocos2d/fast:
	$(MAKE) $(MAKESILENT) -f engine/cocos/lua-bindings/CMakeFiles/luacocos2d.dir/build.make engine/cocos/lua-bindings/CMakeFiles/luacocos2d.dir/build
.PHONY : luacocos2d/fast

#=============================================================================
# Target rules for targets named cpp-empty-test

# Build rule for target.
cpp-empty-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp-empty-test
.PHONY : cpp-empty-test

# fast build rule for target.
cpp-empty-test/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/cpp-empty-test/CMakeFiles/cpp-empty-test.dir/build.make engine/tests/cpp-empty-test/CMakeFiles/cpp-empty-test.dir/build
.PHONY : cpp-empty-test/fast

#=============================================================================
# Target rules for targets named SYNC_RESOURCE-cpp-empty-test

# Build rule for target.
SYNC_RESOURCE-cpp-empty-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SYNC_RESOURCE-cpp-empty-test
.PHONY : SYNC_RESOURCE-cpp-empty-test

# fast build rule for target.
SYNC_RESOURCE-cpp-empty-test/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/cpp-empty-test/CMakeFiles/SYNC_RESOURCE-cpp-empty-test.dir/build.make engine/tests/cpp-empty-test/CMakeFiles/SYNC_RESOURCE-cpp-empty-test.dir/build
.PHONY : SYNC_RESOURCE-cpp-empty-test/fast

#=============================================================================
# Target rules for targets named cpp-tests

# Build rule for target.
cpp-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp-tests
.PHONY : cpp-tests

# fast build rule for target.
cpp-tests/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/cpp-tests/CMakeFiles/cpp-tests.dir/build.make engine/tests/cpp-tests/CMakeFiles/cpp-tests.dir/build
.PHONY : cpp-tests/fast

#=============================================================================
# Target rules for targets named SYNC_RESOURCE-cpp-tests

# Build rule for target.
SYNC_RESOURCE-cpp-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SYNC_RESOURCE-cpp-tests
.PHONY : SYNC_RESOURCE-cpp-tests

# fast build rule for target.
SYNC_RESOURCE-cpp-tests/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/cpp-tests/CMakeFiles/SYNC_RESOURCE-cpp-tests.dir/build.make engine/tests/cpp-tests/CMakeFiles/SYNC_RESOURCE-cpp-tests.dir/build
.PHONY : SYNC_RESOURCE-cpp-tests/fast

#=============================================================================
# Target rules for targets named lua-empty-test

# Build rule for target.
lua-empty-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lua-empty-test
.PHONY : lua-empty-test

# fast build rule for target.
lua-empty-test/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/lua-empty-test/CMakeFiles/lua-empty-test.dir/build.make engine/tests/lua-empty-test/CMakeFiles/lua-empty-test.dir/build
.PHONY : lua-empty-test/fast

#=============================================================================
# Target rules for targets named SYNC_RESOURCE-lua-empty-test

# Build rule for target.
SYNC_RESOURCE-lua-empty-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SYNC_RESOURCE-lua-empty-test
.PHONY : SYNC_RESOURCE-lua-empty-test

# fast build rule for target.
SYNC_RESOURCE-lua-empty-test/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/lua-empty-test/CMakeFiles/SYNC_RESOURCE-lua-empty-test.dir/build.make engine/tests/lua-empty-test/CMakeFiles/SYNC_RESOURCE-lua-empty-test.dir/build
.PHONY : SYNC_RESOURCE-lua-empty-test/fast

#=============================================================================
# Target rules for targets named COPY_LUA-lua-empty-test

# Build rule for target.
COPY_LUA-lua-empty-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 COPY_LUA-lua-empty-test
.PHONY : COPY_LUA-lua-empty-test

# fast build rule for target.
COPY_LUA-lua-empty-test/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/lua-empty-test/CMakeFiles/COPY_LUA-lua-empty-test.dir/build.make engine/tests/lua-empty-test/CMakeFiles/COPY_LUA-lua-empty-test.dir/build
.PHONY : COPY_LUA-lua-empty-test/fast

#=============================================================================
# Target rules for targets named lua-tests

# Build rule for target.
lua-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lua-tests
.PHONY : lua-tests

# fast build rule for target.
lua-tests/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/lua-test/CMakeFiles/lua-tests.dir/build.make engine/tests/lua-test/CMakeFiles/lua-tests.dir/build
.PHONY : lua-tests/fast

#=============================================================================
# Target rules for targets named SYNC_RESOURCE-lua-tests

# Build rule for target.
SYNC_RESOURCE-lua-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SYNC_RESOURCE-lua-tests
.PHONY : SYNC_RESOURCE-lua-tests

# fast build rule for target.
SYNC_RESOURCE-lua-tests/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/lua-test/CMakeFiles/SYNC_RESOURCE-lua-tests.dir/build.make engine/tests/lua-test/CMakeFiles/SYNC_RESOURCE-lua-tests.dir/build
.PHONY : SYNC_RESOURCE-lua-tests/fast

#=============================================================================
# Target rules for targets named COPY_LUA-lua-tests

# Build rule for target.
COPY_LUA-lua-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 COPY_LUA-lua-tests
.PHONY : COPY_LUA-lua-tests

# fast build rule for target.
COPY_LUA-lua-tests/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/lua-test/CMakeFiles/COPY_LUA-lua-tests.dir/build.make engine/tests/lua-test/CMakeFiles/COPY_LUA-lua-tests.dir/build
.PHONY : COPY_LUA-lua-tests/fast

#=============================================================================
# Target rules for targets named HelloCpp

# Build rule for target.
HelloCpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HelloCpp
.PHONY : HelloCpp

# fast build rule for target.
HelloCpp/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/HelloCpp/CMakeFiles/HelloCpp.dir/build.make engine/tests/HelloCpp/CMakeFiles/HelloCpp.dir/build
.PHONY : HelloCpp/fast

#=============================================================================
# Target rules for targets named SYNC_RESOURCE-HelloCpp

# Build rule for target.
SYNC_RESOURCE-HelloCpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SYNC_RESOURCE-HelloCpp
.PHONY : SYNC_RESOURCE-HelloCpp

# fast build rule for target.
SYNC_RESOURCE-HelloCpp/fast:
	$(MAKE) $(MAKESILENT) -f engine/tests/HelloCpp/CMakeFiles/SYNC_RESOURCE-HelloCpp.dir/build.make engine/tests/HelloCpp/CMakeFiles/SYNC_RESOURCE-HelloCpp.dir/build
.PHONY : SYNC_RESOURCE-HelloCpp/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... COPY_LUA-lua-empty-test"
	@echo "... COPY_LUA-lua-tests"
	@echo "... SYNC_RESOURCE-HelloCpp"
	@echo "... SYNC_RESOURCE-cpp-empty-test"
	@echo "... SYNC_RESOURCE-cpp-tests"
	@echo "... SYNC_RESOURCE-lua-empty-test"
	@echo "... SYNC_RESOURCE-lua-tests"
	@echo "... HelloCpp"
	@echo "... cocos2d"
	@echo "... cpp-empty-test"
	@echo "... cpp-tests"
	@echo "... ext_clipper"
	@echo "... ext_convertUTF"
	@echo "... ext_edtaa3func"
	@echo "... ext_luasocket"
	@echo "... ext_md5"
	@echo "... ext_poly2tri"
	@echo "... ext_recast"
	@echo "... ext_tinyxml2"
	@echo "... ext_tolua"
	@echo "... ext_unzip"
	@echo "... ext_xxhash"
	@echo "... ext_xxtea"
	@echo "... external"
	@echo "... lua-empty-test"
	@echo "... lua-tests"
	@echo "... luacocos2d"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

